### PR TITLE
fix(css): Don't modify CSS custom properties

### LINKED ISSUE #397: Can't create a CSS variable with leading underscore(s)
It's not possible to create CSS custom property names with `css()` that start with `--_` or `--__` because the underscores are converted into dashes.

``` r
library(htmltools)

css(
  "--_private-variable" = "private value",
)
#> [1] "---private-variable:private value"
```

This convention is used at times to indicate a locally-scoped or private custom CSS property, which is how we'd like to use `css()` in bslib.

One option would be to update the regex so that underscores that are proceeded by `--` are not replaced with dashes.

Another option would be to add a locally-defined helper function called `var()` that works inside `css()`. It could help with creating CSS variables or with using them, e.g.

```r
red <- "#FF0000"

css(
  var("_private-variable" = "private value"),
  color = var("text-color", red)
)
#> [1] "--_private-variable:private value;color:var(--text-color, #FF0000)"
```

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #397

In the CSS spec, custom properties have to start with `--` and thereafter any character is allowed and is used literally: https://www.w3.org/TR/css-variables-1/#defining-variables

This PR updates `css()` to avoid making any changes to CSS properties in any way, while still conveniently converting camelCase, snake_case and dot.case properties (those that don't start with `--`) to kebab-case.

``` r
css(
  font_size = "12px",
  "--_color" = "red",
  "--is_color" = "true",
  "--thisValueIs" = 42
)
#> [1] "font-size:12px;--_color:red;--is_color:true;--thisValueIs:42;"
```

### CODE REVIEW

File: R/tags.R [hunk 1]
```diff
@@ -1947,8 +1947,16 @@ css <- function(..., collapse_ = "") {
...
+  # Translate camelCase, snake_case, and dot.case to kebab-case
+  # For standard CSS properties only, not CSS variables
+  is_css_var <- grepl("^--", names(props))
+
+  props_std <- names(props)[!is_css_var]
+  props_std <- gsub("([A-Z])", "-\\1", props_std)
+  props_std <- tolower(props_std)
+  props_std <- gsub("[._]", "-", props_std)
+
+  names(props)[!is_css_var] <- props_std
```
Comment (cpsievert) [inline R/tags.R:1959]: I'd find this slightly easier to parse mentally if we wrapped the main logic in a function, say something like:

```r
clean_property_names <- function(x) {
  gsub("[._]", "-", tolower(gsub("([A-Z])", "-\\1", names(props))))
}
```

and then use it like:

```r
names(props)[!is_css_var] <- clean_property_names(
  names(props)[!is_css_var]
)
```

Comment (gadenbuie) [reply R/tags.R]: Sure, although I also find it much easier to parse mentally if we do each step one at a time. So I met in the middle: 3af7643b67e6ffa662d5c4942802f51276aaf1f7

**Review by cpsievert — APPROVED** [review]
Thank you!
